name: client-deploy
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: cd client && npm ci --no-production && npm run build
      - name: copy dist files
        run: cp -R client/dist/* /var/www/esp8266-client
