name: server-deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: cd server && npm install --no-production && npm run build
      - uses: actions/upload-artifact@v2.2.1
        with:
          name: build-files
          path: |
            server/lib
            package-lock.json
            package.json

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v2.0.7
        with:
          name: build-files
          path: /var/www/esp8266-server
      - name: install dependencies
        run: npm run ci --production
        working-directory: /var/www/esp8266-server
      - name: run on PM2
        run: npm run run
        working-directory: /var/www/esp8266-server
